# Site settings
title: Nathaniel Deines
short_title: Nathaniel Deines
description: |
    This is the personal website for Nathaniel Deines.
baseurl: ""
url: "http://opendatahandbook.org" # the base hostname & protocol for your site
github_username:  ndeines
github_repo:  ndeines
contact: mailto:nathaniel.deines@gmail.com

markdown: kramdown

permalink: pretty

defaults:
  -
    scope:
      path: "pages"
    values:
      layout: page
      section: pages
  -
    scope:
      path: "posts"
    values:
      layout: post
      section: posts
